apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web-server
        image: nginx:stable
        volumeMounts:
          - name: rwx-pvc
            mountPath: /usr/share/nginx/html
      volumes:
        - name: rwx-pvc
          persistentVolumeClaim:
            claimName: longhorn-rwx-pvc
