kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
networking:
  disableDefaultCNI: true         # 기본 CNI(kubenet)을 사용하지 않음
  kubeProxyMode: "ipvs"           # kubeproxy 모드를 ipvs 로 설정