apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-full-access
  namespace: backend
subjects:
- kind: Group
  name: backends        
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: backend-full-other-read
  apiGroup: rbac.authorization.k8s.io
