apiVersion: v1
kind: Pod
metadata:
  name: sa-demo-pod
  namespace: default
spec:
  serviceAccountName: wordpress-sa  # 👈 이게 핵심!
  containers:
    - name: demo-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]