apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:junghoon2/k8s-test-manifests.git
    targetRevision: main
    path: foo
    helm:
      valueFiles:
      - ci/values.yaml
  revisionHistoryLimit: 2
