controller:
  replicaCount: 2
  service:
    type: LoadBalancer
    loadBalancerIP: "172.16.224.140"

  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - '{{ include "ingress-nginx.name" . }}'
        - key: app.kubernetes.io/instance
          operator: In
          values:
          - '{{ .Release.Name }}'
        - key: app.kubernetes.io/component
          operator: In
          values:
          - default-backend
      topologyKey: kubernetes.io/hostname