persistence:
  defaultClassReplicaCount: 1

defaultSettings:
  defaultReplicaCount: 1

ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.myweb.com
  tls: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "selfsigned-issuer"