## @param replicaCount Number of NGINX replicas to deploy
replicaCount: 2

resources:
  limits:
     memory: 512Mi
     ephemeral-storage: 2Gi
  requests:
     cpu: 100m
     memory: 128Mi
     ephemeral-storage: 50Mi