wordpressUsername: user

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: wordpress.myweb.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  tls: true

persistence:
  size: 1Gi

mariadb:
  enabled: true
  primary:
    persistence:
      enabled: true
      size: 5Gi
