apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot-01
spec:
  volumeSnapshotClassName: longhorn-snapshot-vsc  # snapshot class 지정
  source:
    persistentVolumeClaimName: data-wordpress-mariadb-0  # 백업 대상 PVC 지정
