global:
  domain: argocd.myweb.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
    ingressClassName: "nginx"
    tls: true