# -- The name of the PriorityClass
priorityClassName: system-node-critical

configmap:
  # -- If enabled, promtail config will be created as a ConfigMap instead of a secret
  enabled: true

defaultVolumes:
  - name: run
    hostPath:
      path: /run/promtail
  - name: containers
    hostPath:
      path: /var/lib/docker/containers
  - name: pods
    hostPath:
      path: /var/log/pods

tolerations:
  - operator: Exists
    effect: NoSchedule
